Iter22
luckyseadog/go-dev pull request #22
Opened 2024-01-10 05:17 UTC by luckyseadog

2024-01-15 22:40 UTC, avhitrov requested changes
1. Необходимо подчистить репозиторий
2. Необходимо допилить graceful shutdown.

2024-01-15 22:40 UTC, avhitrov commented on .DS_Store
Удали из репозитория.

2024-01-15 22:40 UTC, avhitrov commented on certificates/agent/privateKeyAgent.pem
За публикацию приватных ключей в репозитории в любой серьезной компании можно получить хороший нагоняй. А в какой-нибудь Лаборатории Касперского за такое безопасники вообще съедят заживо. Если это тестовые ключи, то надо хотя бы складывать их в папку `certificates-for-testing`, чтобы возникало поменьше вопросов.

2024-01-15 22:40 UTC, avhitrov commented on internal/server/server.go
> +		fmt.Println("shutting down gracefully")
Задание гласит:
```
Данные, которые находятся в процессе обработки на момент получения сигнала, должны быть успешно переданы агентом на сервер, а сервер должен успешно сохранить все несохранённые данные.
```
Соответственно, помимо остановки собственно сервера, необходимо также погасить горутину, которая сохраняет данные на диск, если таковая запущена (например, проканселить контекст или передать в нее по специальному каналу команду на остановку), дождаться ее завершения, позакрывать все хендлеры (файловые, БД) и только потом завершить работу.

2024-01-15 22:40 UTC, avhitrov commented on internal/server/server.go
> +			MyLog.Fatal(err)
С этим надо осторожнее, так как выход по Fatal отменяет все defer-ы.

2024-01-18 09:57 UTC, luckyseadog commented on internal/server/server.go
> +		fmt.Println("shutting down gracefully")
Добрый день, Андрей Владимирович!

А я же в файле cmd/server/main.go в defer делаю закрытие базы данных, отмену горутины(которая сохраняет в файл) и тд. То есть cmd/server/main.go вызывает internal/server/server.go и там завершается сервер, а уже в internal/server/server.go все остальное. Или я не прав?

2024-01-23 22:34 UTC, avhitrov commented on .DS_Store
Файл необходимо удалить

2024-01-23 22:34 UTC, avhitrov commented on internal/agent/agent_methods.go
> +	wg.Add(1)
```suggestion
	wg.Add(3)
```

2024-01-23 22:34 UTC, avhitrov commented on internal/handlers/.DS_Store
Необходимо удалить

2024-01-23 22:34 UTC, avhitrov commented on internal/.DS_Store
Необходимо удалить

2024-01-23 22:34 UTC, avhitrov commented on internal/server/server.go
> +		fmt.Println("shutting down gracefully")
Принимается.

2024-01-23 22:35 UTC, avhitrov approved these changes
Аппрув, но с обещанием поудалять все мусорные файлы из репозитория.

2024-02-08 12:05 UTC, merged